name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: configure
      run: cmake -B build
    - name: make
      run: cmake --build build/
    - name: ssh
      shell: bash
      env: # Or as an environment variable
        ORACLE_SSH: ${{ secrets.ORACLE_SSH }}
        HOST: ${{ secrets.HOST }}
        KNOWN_HOSTS: ${{ secrets.KNOWN_HOSTS }}
        SSH_KEY_PATH: ${{ github.workspace }}/../private.key
      run: |
          mkdir -p ~/.ssh/
          echo "$ORACLE_SSH" > ../private.key
          sudo chmod 600 ../private.key
          echo "$KNOWN_HOSTS" > ~/.ssh/known_hosts
          scp -i $SSH_KEY_PATH ./build/server opc@144.24.177.91:server
          ssh -i $SSH_KEY_PATH opc@144.24.177.91 'server' `</dev/null` >nohup.out 2>&1 &'
